version: "3.8"

services:
  api1:
    image: api:latest
    container_name: api1
    ports:
      - "8001:8000"
    environment:
      APP_ENV: production

  api2:
    image: api:latest
    container_name: api2
    ports:
      - "8002:8000"
    environment:
      APP_ENV: production

  nginx:
    image: nginx:latest
    container_name: nginx-load-balancer
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
